### ISSUE TITLE
Unnecessarily indents css classes on each run

### ISSUE THREAD

**Issue by anildigital** [surface-ui/surface_formatter#36]
Bug can be reproduced on this sample repo https://github.com/anildigital/surface_formatter_bug

`$ mix surface.format`

```
<TextInput
  class={
    "w-full h-12 max-w-full px-4 bg-xxx-100 hover:bg-xxx-120 text-base leading-normal
     text-color-yyy-100 box-border border border-solid border-kkk-100 rounded transition
     ease-in placeholder-hhh-100 placeholder-opacity-100 disabled:opacity-50
     disabled:cursor-not-allowed focus:border-mmmm-100 focus:outline-none
     no-scrollbar invalid:shadow-none invalid:border-ttt-100 #{@class}",
```

Then run again

`$ mix surface.format`

```
<TextInput
  class={
    "w-full h-12 max-w-full px-4 bg-xxx-100 hover:bg-xxx-120 text-base leading-normal
          text-color-yyy-100 box-border border border-solid border-kkk-100 rounded transition
          ease-in placeholder-hhh-100 placeholder-opacity-100 disabled:opacity-50
          disabled:cursor-not-allowed focus:border-mmmm-100 focus:outline-none
          no-scrollbar invalid:shadow-none invalid:border-ttt-100 #{@class}",
```

then run again

``$ mix surface.format``

```
<TextInput
  class={
    "w-full h-12 max-w-full px-4 bg-xxx-100 hover:bg-xxx-120 text-base leading-normal
                text-color-yyy-100 box-border border border-solid border-kkk-100 rounded transition
                ease-in placeholder-trunks-100 placeholder-opacity-100 disabled:opacity-50
                disabled:cursor-not-allowed focus:border-mmmm-100 focus:outline-none
                no-scrollbar invalid:shadow-none invalid:border-ttt-100 #{@class}",
```

**Comment by paulstatezny** [comment]
@anildigital This behavior has been fixed as of version 0.5.2, published a few minutes ago. Let me know if you experience more problems!

**Comment by v0idpwn** [comment]
Hey! II bumped surface_formatter to 0.5.2 and it still happens here.

**Comment by anildigital** [comment]
@paulstatezny I will share an example

**Comment by anildigital** [comment]
@paulstatezny This bug can be reproduced on this example https://github.com/anildigital/surface_formatter_bug

**Comment by paulstatezny** [comment]
@anildigital I believe it should all be fixed now. Thanks again for reporting. Try out v0.5.3 and let me know if you're still experiencing the problem.

**Comment by anildigital** [comment]
@paulstatezny Still getting the same issue even with `0.5.3`. 

![image](https://user-images.githubusercontent.com/266/131452074-82b32e6b-3e50-4e32-96c8-d206733b9d7b.png)

![image](https://user-images.githubusercontent.com/266/131452141-61ace025-dbb3-42a9-8611-286000f8f351.png)

**Comment by paulstatezny** [comment]
@anildigital Thanks for your patience. I did some refactoring to clean up some tech debt to make isolating and exploring the problem easier. It should be fixed now in v0.5.4 (third time's a charm!), but can you post back to confirm or deny from your end?

Thanks for going back and forth with me!

**Comment by anildigital** [comment]
@paulstatezny It seems to work, but there is an issue I guess, it indents using 'tab' char instead of 'space'

![image](https://user-images.githubusercontent.com/266/131617796-ccce0564-9809-482f-90fd-869bb83ad747.png)

**Comment by paulstatezny** [comment]
Now we are fully in the Twilight Zone. 😂

I'll take a look. Thanks @anildigital.

**Comment by paulstatezny** [comment]
@anildigital I cloned https://github.com/anildigital/surface_formatter_bug, bumped to v0.5.4, and it's not modifying `lib/surface_formatter_bug_web/live/text_input_new.ex`.

```
$ mix surface.format lib/surface_formatter_bug_web/live/text_input_new.ex
$ git status
                                                                09:36:02
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   mix.exs
	modified:   mix.lock

```

Is it possible the tab characters are from your editor? The formatter doesn't introduce tab characters and never has, so I don't see how it's possible those are coming from it.

**Comment by anildigital** [comment]
@paulstatezny  Thanks a lot for the help.

You may be right about tabs. Not able to reproduce format adding `tabs` now.

But to test, I manually wrongly formatted classes and expected "surface formatter" to format those. But there is no change at all.  Is this expected?

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/266/131712818-351e225b-4643-4606-9fa9-be8b7a6e5a74.png">

or 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/266/131712983-cabdedf6-7544-423d-9a6d-9daa80a4655a.png">

**Comment by paulstatezny** [comment]
@anildigital Yes, this is expected. I've added a new section that explains how this affects string attributes/props:

---

https://hexdocs.pm/surface_formatter/0.5.4/Surface.Formatter.html#format_string!/2-whitespace-in-string-attributes

> ## Code semantics must be maintained 
>
> It's critical that a code formatter never change the semantics of the code it modifies.  In other words, the behavior of a program should never change due to a code formatter.
>
> The **Whitespace** section above outlines how `SurfaceFormatter` preserves code semantics by refusing to modify contents of `<script>`, `<code>` and `<pre>` tags as well as macro components. And for the same reason, the formatter does not introduce whitespace between HTML tags when there is none.
>
> ## Code semantics in string attributes 
>
> `SurfaceFormatter` cannot reliably guess whether application behavior will be changed by formatting the contents of a string. For example, consider a component with the following interface:
>
> ```html
> <List items="
> apples (fuji)
> oranges (navel)
> bell peppers (green)
> " />
> ```
>
> The component internally splits on newline characters and outputs the following HTML:
>
> ```html
> <ul>
>   <li>apples (fuji)</li>
>   <li>oranges (navel)</li>
>   <li>bell peppers (green)</li>
> </ul>
> ```
>
> If `SurfaceFormatter` assumes it is safe to modify whitespace in string attributes, then the Surface code would likely change to this:
>
> ```html
> <List items="apples (fuji) oranges (navel) bell peppers (green)" />
> ```
>
> Which would output the following HTML:
>
> ```html
> <ul>
>   <li>apples (fuji) oranges (navel) bell peppers (green)</li>
> </ul>
> ```
>
> Notice that the behavior of the application would have changed simply by running the formatter. It is for this reason that `SurfaceFormatter` always retains precisely the same whitespace in attribute strings, including both space and newline characters.

---

Some might feel this is a rare case that should be ignored, or that attributes/props named `class` should be treated differently. And if there's enough support perhaps we should consider ways to customize this behavior. However, until there's a clear reason to change I've been intentionally conservative.

**Comment by anildigital** [comment]
Thanks @paulstatezny !

**Comment by krushi123** [comment]
@paulstatezny That is a very instructive paragraph regarding code semantics. Thanks for the documentation.
