### ISSUE TITLE
Weird formatting of <code> node inside <pre> node in Surface Catalogue 

### ISSUE THREAD

**Issue by tiagoefmoraes** [surface-ui/surface_formatter#64]
I [formatted surface_catalogue](https://github.com/surface-ui/surface_catalogue/commit/65b850c7c8ff7a7d7c1122d2f30e5ab0de71c2ec) using the main surface branch and found [this change](https://github.com/surface-ui/surface_catalogue/commit/65b850c7c8ff7a7d7c1122d2f30e5ab0de71c2ec#diff-02eaac6d9911de90de16ae0d200d87bff2eb2efe08703a826a9a56faf6da38aeR151-R161) weird.

Before

```html
                      <div class="code" style={"width: #{example.code_perc}%"}>
                        <pre class="language-surface">
                          <code class="content language-surface" phx-hook="Highlight" id={"example-code-#{index}-#{example.func}"}>
    {example.code}</code>
                        </pre>
                      </div>
```

After

```html
                      <div class="code" style={"width: #{example.code_perc}%"}>
                        <pre class="language-surface">
                          <code
      class="content language-surface"
      phx-hook="Highlight"
      id={"example-code-#{index}-#{example.func}"}
    >
    {example.code}</code>
                        </pre>
                      </div>
```

**Comment by paulstatezny** [comment]
@tiagoefmoraes So sorry for the delay in responding to this.

I did see it when you first submitted it, and since got distracted with work and life.

Do you know if it's since been fixed in Surface itself? If not, I'll try to take a look in the next couple weeks.

**Comment by tiagoefmoraes** [comment]
> @tiagoefmoraes So sorry for the delay in responding to this.
> 
> I did see it when you first submitted it, and since got distracted with work and life.
> 
> Do you know if it's since been fixed in Surface itself? If not, I'll try to take a look in the next couple weeks.

I think it was not solved but I'm not able to test it right now.

**Comment by paulstatezny** [comment]
@tiagoefmoraes Thanks again for reporting this!

I attempted to reproduce it, but I wasn't successful. Here's where I ended up with the test I was using to play around with it:

```elixir
test "issue 64" do
  assert_formatter_outputs(
    ~S"""
    <div>
      <div>
        <div>
          <div>
            <div>
              <code class="very-long-class-to-increase-length-of-the-line" phx-hook="VeryLongHookToIncreaseLengthOfTheLine" id={"interpolated-#{index}"}>
            {example.code}</code>
            </div>
          </div>
        </div>
      </div>
    </div>
    """,
    ~S"""
    <div>
      <div>
        <div>
          <div>
            <div>
              <code
                class="very-long-class-to-increase-length-of-the-line"
                phx-hook="VeryLongHookToIncreaseLengthOfTheLine"
                id={"interpolated-#{index}"}
              >
            {example.code}</code>
            </div>
          </div>
        </div>
      </div>
    </div>
    """
  )
end
```

(The test passes.)

Note that [surface_formatter considers the contents of `<code>` tags whitespace-sensitive](https://hexdocs.pm/surface_formatter/Surface.Formatter.html#format_string!/2-whitespace-that-exists), and therefore it's intentional that your "outdented" `{example.code}` stays outdented.

However, the attributes of `<code>` (namely `class`, `phx-hook`, and `id`) should be intended in alignment with the start of the opening `<code>` tag. Which, you can see in the test case above, does happen with the latest version of surface_formatter.

I'm going to close this ticket, but of course feel free to reply if new information or related scenarios appear! Thanks again.
